# Generated by Django 4.2.2 on 2023-06-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=300)),
                ('owner', models.CharField(max_length=200)),
                ('schedule', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.job')),
            ],
        ),
    ]
