# Generated by Django 4.2.2 on 2023-06-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
